# https://github.com/mattn/go-sqlite3#dsn-examples
database: "file:store.db"
telegram:
  token: ""
  debug: true
discord:
  token: ""
  channel_id: ""
#proxy:
#  host: ""
#  port: ""
#  user: ""
#  password: ""